spring.application.name=vault_finance
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/vaulta_database
spring.datasource.username=erik
spring.datasource.password=Elements@2025

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=debug

# Como você já criou as tabelas manualmente:
spring.flyway.enabled=false
